backend:
  name: git-gateway
  repo: tsaristbomba/page-blog-starter
  branch: master

media_folder: content/assets
public_folder: ../assets
locale: "pt"

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: date, label: Data, widget: date }
      - { name: image, label: Imagem Thumbnail, widget: image, required: false }
      - { name: title, label: Título }
      - { name: description, label: Descrição }
      - { name: body, label: Texto, widget: markdown }
