backend:
  name: github
  repo: tsaristbomba/page-blog-starter

media_folder: content/assets
public_folder: ../assets
locale: "pt-br"

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: date, label: Data, widget: date }
      - {
          name: thumbnail,
          label: Imagem Thumbnail,
          widget: image,
          required: false,
        }
      - { name: title, label: Título }
      - { name: description, label: Descrição }
      - { name: body, label: Texto, widget: markdown }
